[utils] remove the invalid function call to walk_packages
Logger class instance in install_package function is calling walk_packages
function instead of warning. There is no member name walk_packages in Logger
class and on execution it lead to following error:

AttributeError: 'Logger' object has no attribute 'walk_packages'

This patch updates the function to log the warning message if package
manager is not available.

Signed-off-by: Sourabh Jain <sourabhjain@linux.ibm.com>